id = "systemd-support"
name = "Systemd Support"
version = "0.1.0"
schema_version = 1
authors = ["10fish <jokefish@live.com>"]
description = "An extension for work with linux systemd unit files."
repository = "https://github.com/10fish/systemd-support.git"

[language_servers.systemd]
name = "Systemd"
language = "Unit File"
file_extensions = [
    "service",
    "socket",
    "device",
    "mount",
    "automount",
    "swap",
    "target",
    "path",
    "timer",
    "slice",
]

[grammars.systemd]
repository = "https://github.com/10fish/tree-sitter-systemd"
commit = "13e65e58a895f22f027d6f460fcd4cb79996d866"
